function j1c(){}
function A2c(){}
function R2c(){}
function Z2c(){}
function X2c(){}
function c3c(){}
function a3c(){}
function f3c(){}
function n_d(){}
function h_d(){}
function h3c(b){this.b=b}
function w2c(){q2c.call(this)}
function PR(b){b.c.bf(QN(b.b.b))}
function nJ(b,c,d){return new C2c(b,c,d)}
function C2c(b,c,d){iY.call(this,b,c);this.d=d;Tld(this.j,275).Wc(this)}
function p_d(){k_d=new n_d;Zad((Wad(),Vad),19);!!$stats&&$stats(Obd(D4f,Bif,-1,-1));k_d.Ve();!!$stats&&$stats(Obd(D4f,dFf,-1,-1))}
function m_d(){var b,d,e;while(i_d){d=c9c;e=i_d;i_d=i_d.c;!i_d&&(j_d=null);if(!d){PR(e.b)}else{try{PR(e.b)}catch(b){b=ZVd(b);if(!Wld(b,209))throw b}}}}
function QN(b){var c;!b.Ac&&(b.Ac=(c=nJ((!b.Jc&&(b.Jc=new Tne),b.Jc),(!b.Bc&&(b.Bc=new U2c),b.Bc),(!b.zc&&(b.zc=new J2c),b.zc),!b.Ic&&(b.Ic=(new Kme).hf(new tme,new xme))),c.Pc(),c));return b.Ac}
function i1c(){var b,c,d,e,f,g,i,j;if(g1c){return g1c}else{g1c=new w2c;v1c(g1c,g4f,h4f,false);g=new Xse;g.M[i4f]=(fBe(),bBe).b;g.M[j4f]=(tBe(),pBe).b;b=new Xse;b.M[i4f]=_Ae.b;b.M[j4f]=pBe.b;j=new Xse;j.M[i4f]=dBe.b;j.M[j4f]=pBe.b;i=new Xse;i.M[i4f]=cBe.b;i.M[j4f]=pBe.b;y1c(g1c,k4f,Fld(XUd,{272:1,322:1},105,[g,b,j,i]));c=new eue(l4f,m4f);aIe(c.M,NEf,(bVe(),bVe(),aVe));d=new eue(n4f,o4f);d.M[p4f]=q4f;e=new eue(r4f,s4f);f=new eue(t4f,u4f);Y1c(g1c,Fld(VUd,{272:1,322:1},103,[c,d,e,f]));v1c(g1c,v4f,$bd()+w4f,false);v1c(g1c,x4f,$bd()+y4f,false);return g1c}}
function U2c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new evb;d=new cJe;Rhb(d,hef,(CEe(),wEe).b,true);Vhb(d,tef,QWe(2));Qhb(d)?(i=d.fd(),i.setProperty(Tcf,Qcf),undefined):(d.o[Tcf]=Qcf,undefined);Qhb(d)?(n=d.fd(),n.setProperty(Pcf,20),undefined):(d.o[Pcf]=20,undefined);Qhb(d)?(q=d.fd(),q.setProperty(eef,z4f),undefined):(d.o[eef]=z4f,undefined);c=new SIe(A4f);Dib(c,new Z2c);e=new LTe;b=new RTe;Qhb(b)?(t=b.fd(),t.setProperty(qGf,rGf),undefined):(b.o[qGf]=rGf,undefined);Qhb(b)?(w=b.fd(),w.setProperty(sGf,Qmf),undefined):(b.o[sGf]=Qmf,undefined);Dib(b,new h3c(this));JTe(e,b);Xub(this.b,Fld(zVd,{272:1,322:1},137,[d,c,e,(this.c=new hkb,Wib(this.c),Sib(this.c),Xhb(this.c,FHf,(bVe(),bVe(),aVe),true),Uhb(this.c,TEf,0,true),x=new nQe(l4f),y=new nQe(n4f),z=new nQe(r4f),A=new nQe(t4f),Thb(this.c,QEf,Fld(EVd,{272:1,322:1},190,[x,y,z,A]),true),Xhb(this.c,wGf,aVe,true),Xhb(this.c,SEf,aVe,true),Whb(this.c,PEf,t1c(i1c())),Xhb(this.c,REf,aVe,false),Uhb(this.c,TEf,0,true),Xhb(this.c,REf,aVe,false),Xhb(this.c,xGf,aVe,true),Xhb(this.c,a2f,aVe,true),this.c)]))}
var h4f='/response/data/recordlist/*',z4f='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',M4f='AsyncLoader19',B4f='DATA',m4f='Data 1',o4f='Data 2',s4f='Data 3',u4f='Data 4',A4f='Test RPC',F4f='TestRestDataSourceData$1',G4f='TestRestDataSourcePresenter',y4f='TestRestDataSourceServlet?method=add',w4f='TestRestDataSourceServlet?method=fetch',C4f='TestRestDataSourceServlet?method=rpc',I4f='TestRestDataSourceView',J4f='TestRestDataSourceView$1',K4f='TestRestDataSourceView$1$1',L4f='TestRestDataSourceView$2',E4f='com.gdn.venice.client.app.testrestdatasource.data.',H4f='com.gdn.venice.client.app.testrestdatasource.view.',l4f='data1',n4f='data2',q4f='data2/name',r4f='data3',t4f='data4',D4f='runCallbacks19',p4f='valueXPath';var g1c=null;_=w2c.prototype=j1c.prototype=new k1c;_.gC=function x2c(){return BKd};_.te=function y2c(b){var c;return c=this.ud(),c.__transformRequest(b.fd())};_.ue=function z2c(b,c,d){var e;e=this.ud();e.__transformResponse(b.fd(),c.fd(),d)};_.cM={87:1,217:1,319:1};_=C2c.prototype=A2c.prototype=new NX;_.gC=function D2c(){return EKd};_.Rc=function E2c(){Sne(this.g,this,new Rqe((S3c(),Q3c),this))};_.cM={87:1,309:1};_=U2c.prototype=R2c.prototype=new yZ;_.Xc=function V2c(){return this.b};_.gC=function W2c(){return IKd};_.cM={275:1};_.b=null;_.c=null;_=Z2c.prototype=X2c.prototype=new aI;_.gC=function $2c(){return GKd};_.Yc=function _2c(b){var c;c=new mse;c.M[Hdf]=B4f;c.M[Idf]=$bd()+C4f;c.M[Kdf]=Ldf;aIe(c.M,Mdf,(bVe(),bVe(),aVe));aIe(c.M,Ndf,_Ue);Uze(c,new c3c)};_.cM={292:1,324:1};_=c3c.prototype=a3c.prototype=new aI;_.Sc=function d3c(b,c,d){$wnd.isc.say(kKf)};_.gC=function e3c(){return FKd};_.cM={};_=h3c.prototype=f3c.prototype=new aI;_.gC=function i3c(){return HKd};_.Yc=function j3c(b){var c;c=this.b.c.ud();c.startEditingNew()};_.cM={292:1,324:1};_.b=null;_=n_d.prototype=h_d.prototype=new aI;_.gC=function o_d(){return $Md};_.Ve=function s_d(){m_d()};_.cM={};var BKd=sVe(E4f,F4f),EKd=sVe(Yuf,G4f),IKd=sVe(H4f,I4f),GKd=sVe(H4f,J4f),FKd=sVe(H4f,K4f),HKd=sVe(H4f,L4f),$Md=sVe(Uyf,M4f);$entry(p_d)();