function yGb(){}
function Q0b(){}
function X0b(){}
function a1b(){}
function f1b(){}
function F1d(){}
function z1d(){}
function c1b(b){this.b=b}
function h1b(b){this.b=b}
function Z0b(b,c){this.b=b;this.c=c}
function QS(b){b.c.bf(pN(b.b.b))}
function SI(b,c,d){return new BGb(b,c,d)}
function BGb(b,c,d){iY.call(this,b,c);this.d=d;Tld(this.j,50).Wc(this);Tld(Tld(this.j,50).Xc(),3).b=Tld(this.d,51).Tc()}
function H1d(){C1d=new F1d;Zad((Wad(),Vad),24);!!$stats&&$stats(Obd(zcg,Bif,-1,-1));C1d.Ve();!!$stats&&$stats(Obd(zcg,dFf,-1,-1))}
function E1d(){var b,d,e;while(A1d){d=c9c;e=A1d;A1d=A1d.c;!A1d&&(B1d=null);if(!d){QS(e.b)}else{try{QS(e.b)}catch(b){b=ZVd(b);if(!Wld(b,209))throw b}}}}
function pN(b){var c;!b.Y&&(b.Y=(c=SI((!b.Jc&&(b.Jc=new Tne),b.Jc),(!b.qb&&(b.qb=new U0b),b.qb),(!b.X&&(b.X=new IGb),b.X),!b.Ic&&(b.Ic=(new Kme).hf(new tme,new xme))),c.Pc(),c));return b.Y}
function T0b(b,c){var d;d=new hkb;Xhb(d,REf,(bVe(),bVe(),aVe),false);Xhb(d,xGf,aVe,true);Xhb(d,yGf,aVe,true);Xhb(d,SEf,aVe,true);Whb(d,PEf,t1c(c));Thb(d,QEf,P5c(c),true);yjb(d,scg).M[Tcf]=_Ef;L5c(yjb(d,qcg));Xub(b.d,Fld(zVd,{272:1,322:1},137,[d]))}
function AGb(b){var c,d,e,f;c=(d=Fld(VUd,{272:1,322:1},103,[new eue(ocg,kNf),new eue(pcg,Ryf),new eue(qcg,iEf),new eue(rcg,QPf),new eue(scg,sNf)]),aIe(d[0].M,NEf,(bVe(),bVe(),aVe)),f=new o3c($bd()+tcg,null,null,null,d),e=new v4e,b!=null?e.pl(pcg,b):e.pl(pcg,gcf),fIe(n3c(f,(fBe(),bBe)).M,fHf,e),f);return c}
function U0b(){var b,c,d,e,f,j,o,r,u,x,A,D,G,J,M;this.b=new RMe;this.c=new w8c;d=new LTe;Qhb(d)?(j=d.fd(),j.setProperty(Tcf,Qcf),undefined):(d.o[Tcf]=Qcf,undefined);c=new Wsb;Qhb(c)?(o=c.fd(),o.setProperty(eXf,50),undefined):(c.o[eXf]=50,undefined);Vhb(c,wIf,QWe(10));Qhb(c)?(r=c.fd(),r.setProperty(Tcf,150),undefined):(c.o[Tcf]=150,undefined);GLe(this.b,eif,Ryf);JLe(this.b,new Hkd);GLe(this.b,fXf,(bAe(),_ze).b);GLe(this.b,gef,aAe.b);e=new LPb;Qhb(e)?(u=e.fd(),u.setProperty(Pcf,STf),undefined):(e.o[Pcf]=STf,undefined);b=new RTe;Qhb(b)?(x=b.fd(),x.setProperty(Tcf,150),undefined):(b.o[Tcf]=150,undefined);Qhb(b)?(A=b.fd(),A.setProperty(eif,Cff),undefined):(b.o[eif]=Cff,undefined);Qhb(b)?(D=b.fd(),D.setProperty(qGf,zIf),undefined):(b.o[qGf]=zIf,undefined);Rhb(b,gef,aAe.b,true);Dib(b,new Z0b(this,b));f=new RTe;Qhb(f)?(G=f.fd(),G.setProperty(qGf,zIf),undefined):(f.o[qGf]=zIf,undefined);Qhb(f)?(J=f.fd(),J.setProperty(sGf,ucg),undefined):(f.o[sGf]=ucg,undefined);Qhb(f)?(M=f.fd(),M.setProperty(eif,vcg),undefined):(f.o[eif]=vcg,undefined);Dib(f,new h1b(this));Usb(c,Fld(BVd,{272:1,322:1},171,[this.b]));Xub(e,Fld(zVd,{272:1,322:1},137,[b,f]));this.d=new evb;Xub(this.c,Fld(zVd,{272:1,322:1},137,[d,c,e,this.d]))}
var Fcg='AsyncLoader24',ycg='Calculating risk points...',ucg='Click here to Show Order detail.',Acg='FraudCalculatePresenter',xcg='FraudCalculatePresenterServlet?Date=',Bcg='FraudCalculateView',Ccg='FraudCalculateView$1',Dcg='FraudCalculateView$1$1',Ecg='FraudCalculateView$2',tcg='FraudCaseMaintenancePresenterServlet?method=fetchOrderCalculateFraud&type=DataSource',vcg='Show Order',qcg='VenOrderPaymentAllocation.venOrder.amount',pcg='VenOrderPaymentAllocation.venOrder.orderDate',rcg='VenOrderPaymentAllocation.venOrder.venCustomer.customerUserName',scg='VenOrderPaymentAllocation.venOrder.venOrderStatus.orderStatusCode',zcg='runCallbacks24';_=BGb.prototype=yGb.prototype=new NX;_.gC=function CGb(){return $ud};_.Rc=function DGb(){Sne(this.g,this,new Rqe((S3c(),Q3c),this))};_.cM={87:1,215:1,309:1};_=U0b.prototype=Q0b.prototype=new yZ;_.Xc=function V0b(){return this.c};_.gC=function W0b(){return mzd};_.cM={50:1};_.c=null;_.d=null;_=Z0b.prototype=X0b.prototype=new aI;_.gC=function $0b(){return kzd};_.Yc=function _0b(b){var c,d,e,f,j;Xhb(this.c,SLf,(bVe(),aVe),true);f=new mse;c=PMe(this.b.b);d=(Aid(),ojd(wcg,Ajd((zjd(),zjd(),yjd))));e=(j=ikd(c.q.getTimezoneOffset()),Eid(d,c,j));f.M[Idf]=$bd()+xcg+e;f.M[Kdf]=Ldf;aIe(f.M,Mdf,aVe);$wnd.isc.RPCManager.addClassProperties({promptStyle:(WEe(),VEe).Uk()});dHe();$wnd.isc.RPCManager.defaultPrompt=ycg;$wnd.isc.RPCManager.showPrompt=true;Uze(f,new c1b(this.c))};_.cM={292:1,324:1};_.b=null;_.c=null;_=c1b.prototype=a1b.prototype=new aI;_.Sc=function d1b(b,c,d){var e;e=c.tM==$6e||c.cM&&!!c.cM[1]?c.tS():c.toString?c.toString():Kcf;$wnd.isc.say(e);Xhb(this.b,SLf,(bVe(),_Ue),true);dHe();$wnd.isc.RPCManager.defaultPrompt=kOf};_.gC=function e1b(){return jzd};_.cM={};_.b=null;_=h1b.prototype=f1b.prototype=new aI;_.gC=function i1b(){return lzd};_.Yc=function j1b(b){var c,d,e,i;c=PMe(this.b.b);d=(Aid(),ojd(wcg,Ajd((zjd(),zjd(),yjd))));e=(i=ikd(c.q.getTimezoneOffset()),Eid(d,c,i));T0b(this.b,AGb((Tld(this.b.B,215),e)))};_.cM={292:1,324:1};_.b=null;_=F1d.prototype=z1d.prototype=new aI;_.gC=function G1d(){return qNd};_.Ve=function K1d(){E1d()};_.cM={};var $ud=sVe(Ktf,Acg),mzd=sVe(fFf,Bcg),kzd=sVe(fFf,Ccg),jzd=sVe(fFf,Dcg),lzd=sVe(fFf,Ecg),qNd=sVe(Uyf,Fcg);$entry(H1d)();