function KSc(){}
function BUc(){}
function HUc(){}
function uZd(){}
function oZd(){}
function UQ(b){b.c.gf(MN(b.b.b))}
function JUc(){Ahb();gkb.call(this)}
function MSc(b,c,d){hY.call(this,b,c);this.d=d;Dld(this.j,265).Wc(this);Dld(Dld(this.j,265).Xc(),3).b=Dld(this.d,266).Tc()}
function wZd(){rZd=new uZd;Xad((Uad(),Tad),15);!!$stats&&$stats(Mbd(j_f,fjf,-1,-1));rZd.Ue();!!$stats&&$stats(Mbd(j_f,zHf,-1,-1))}
function tZd(){var b,d,e;while(pZd){d=b9c;e=pZd;pZd=pZd.c;!pZd&&(qZd=null);if(!d){UQ(e.b)}else{try{UQ(e.b)}catch(b){b=IVd(b);if(!Gld(b,209))throw b}}}}
function MN(b){var c;!b.qc&&(b.qc=(c=new MSc((!b.Jc&&(b.Jc=new voe),b.Jc),(!b.wc&&(b.wc=new EUc),b.wc),(!b.pc&&(b.pc=new TSc),b.pc)),c.Pc(),c));return b.qc}
function pSc(){var b,c,d;if(nSc){return nSc}else{nSc=new $1c;nSc.se(a_f);b=new Iue(gdf,b_f);EIe(b.M,yFf,(FVe(),FVe(),EVe));d=new Iue(ZNf,GOf);c=new Iue(Jif,c_f);X1c(nSc,pld(EUd,{272:1,321:1},103,[b,d,c]));nSc.re(d_f);v1c(nSc,e_f,EVe,false);return nSc}}
function EUc(){var b,c,d,e,f,g,i,j;this.b=new v8c;Wub(this.b,pld(iVd,{272:1,321:1},137,[(e=new JUc,Phb(e)?(g=e.fd(),g.setProperty(wdf,tdf),undefined):(e.o[wdf]=tdf,undefined),Phb(e)?(i=e.fd(),i.setProperty(sdf,tdf),undefined):(e.o[sdf]=tdf,undefined),Whb(e,SGf,(FVe(),FVe(),EVe),true),Whb(e,f_f,EVe,true),Tjb(e,EVe),Phb(e)?(j=e.fd(),j.setProperty(TGf,0),undefined):(e.o[TGf]=0,undefined),b=new UQe(gdf,b_f,100),f=new TQe(ZNf,GOf),c=new TQe(Jif,c_f),d=new UQe(g_f,h_f,200),Phb(e)?cib(e,fGf,OHe(pld(nVd,{272:1,321:1},190,[b,f,c,d]))):(e.o[fGf]=OHe(pld(nVd,{272:1,321:1},190,[b,f,c,d])),undefined),Whb(e,UGf,EVe,true),Whb(e,VGf,EVe,true),Vhb(e,eGf,s1c(pSc())),Whb(e,gGf,EVe,false),Phb(e)?undefined:(e.o[YKf]=ZNf,undefined),Rhb(e,(sDe(),pDe)),Whb(e,WGf,EVe,true),Whb(e,b$f,EVe,true),e)]))}
var a_f='/tasklaunchpad/tasks/task',n_f='AsyncLoader15',h_f='Start',k_f='TaskLaunchpadPresenter',l_f='TaskLaunchpadView',m_f='TaskLaunchpadView$1',i_f='[SKIN]/icons/play.png',d_f='ds/test_data/tasklaunchpad.data.xml',j_f='runCallbacks15',g_f='startField';var nSc=null;_=MSc.prototype=KSc.prototype=new MX;_.gC=function NSc(){return yId};_.Rc=function OSc(){uoe(this.g,this,new tre((R3c(),P3c),this))};_.cM={87:1,308:1};_=EUc.prototype=BUc.prototype=new xZ;_.Xc=function FUc(){return this.b};_.gC=function GUc(){return OId};_.cM={265:1};_.b=null;_=JUc.prototype=HUc.prototype=new ehb;_.Gd=function KUc(b,c){var d,e,i,n,q,t;e=zjb(this,c.b);if(uYe(e,g_f)){d=new _Je;Phb(d)?(i=d.fd(),i.setProperty(sdf,18),undefined):(d.o[sdf]=18,undefined);Phb(d)?(n=d.fd(),n.setProperty(wdf,65),undefined):(d.o[wdf]=65,undefined);Phb(d)?(q=d.fd(),q.setProperty(BGf,i_f),undefined):(d.o[BGf]=i_f,undefined);Phb(d)?(t=d.fd(),t.setProperty(Kif,h_f),undefined):(d.o[Kif]=h_f,undefined);return d}else{return null}};_.gC=function LUc(){return NId};_.cM={69:1,86:1,87:1,91:1,93:1,94:1,95:1,136:1,137:1,138:1,139:1,140:1,141:1,142:1,143:1,144:1,145:1,146:1,147:1,148:1,149:1,150:1,151:1,152:1,153:1,154:1,155:1,156:1,157:1,158:1,159:1,160:1,161:1,162:1,163:1,164:1,165:1,166:1,167:1,168:1,169:1,192:1,195:1,196:1,197:1};_=uZd.prototype=oZd.prototype=new _H;_.gC=function vZd(){return uMd};_.Ue=function zZd(){tZd()};_.cM={};var yId=WVe(bwf,k_f),OId=WVe(mTf,l_f),NId=WVe(mTf,m_f),uMd=WVe(eAf,n_f);$entry(wZd)();