function f1c(){}
function w2c(){}
function N2c(){}
function V2c(){}
function T2c(){}
function $2c(){}
function Y2c(){}
function b3c(){}
function O$d(){}
function I$d(){}
function d3c(b){this.b=b}
function s2c(){m2c.call(this)}
function LR(b){b.c.Ze(MN(b.b.b))}
function jJ(b,c,d){return new y2c(b,c,d)}
function y2c(b,c,d){eY.call(this,b,c);this.d=d;wld(this.j,275).Wc(this)}
function Q$d(){L$d=new O$d;Vad((Sad(),Rad),19);!!$stats&&$stats(Kbd(U3f,Xhf,-1,-1));L$d.Re();!!$stats&&$stats(Kbd(U3f,uEf,-1,-1))}
function N$d(){var b,d,e;while(J$d){d=$8c;e=J$d;J$d=J$d.c;!J$d&&(K$d=null);if(!d){LR(e.b)}else{try{LR(e.b)}catch(b){b=yVd(b);if(!zld(b,209))throw b}}}}
function MN(b){var c;!b.Ac&&(b.Ac=(c=jJ((!b.Jc&&(b.Jc=new nne),b.Jc),(!b.Bc&&(b.Bc=new Q2c),b.Bc),(!b.zc&&(b.zc=new F2c),b.zc),!b.Ic&&(b.Ic=(new eme).df(new Ple,new Tle))),c.Pc(),c));return b.Ac}
function e1c(){var b,c,d,e,f,g,i,j;if(c1c){return c1c}else{c1c=new s2c;r1c(c1c,x3f,y3f,false);g=new rse;g.M[z3f]=(BAe(),xAe).b;g.M[A3f]=(PAe(),LAe).b;b=new rse;b.M[z3f]=vAe.b;b.M[A3f]=LAe.b;j=new rse;j.M[z3f]=zAe.b;j.M[A3f]=LAe.b;i=new rse;i.M[z3f]=yAe.b;i.M[A3f]=LAe.b;u1c(c1c,B3f,ild(wUd,{272:1,322:1},105,[g,b,j,i]));c=new Ate(C3f,D3f);wHe(c.M,cEf,(xUe(),xUe(),wUe));d=new Ate(E3f,F3f);d.M[G3f]=H3f;e=new Ate(I3f,J3f);f=new Ate(K3f,L3f);U1c(c1c,ild(uUd,{272:1,322:1},103,[c,d,e,f]));r1c(c1c,M3f,Wbd()+N3f,false);r1c(c1c,O3f,Wbd()+P3f,false);return c1c}}
function Q2c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new avb;d=new yIe;Nhb(d,Ddf,(YDe(),SDe).b,true);Rhb(d,Pdf,kWe(2));Mhb(d)?(i=d.fd(),i.setProperty(ncf,kcf),undefined):(d.o[ncf]=kcf,undefined);Mhb(d)?(n=d.fd(),n.setProperty(jcf,20),undefined):(d.o[jcf]=20,undefined);Mhb(d)?(q=d.fd(),q.setProperty(Adf,Q3f),undefined):(d.o[Adf]=Q3f,undefined);c=new mIe(R3f);zib(c,new V2c);e=new fTe;b=new lTe;Mhb(b)?(t=b.fd(),t.setProperty(HFf,IFf),undefined):(b.o[HFf]=IFf,undefined);Mhb(b)?(w=b.fd(),w.setProperty(JFf,imf),undefined):(b.o[JFf]=imf,undefined);zib(b,new d3c(this));dTe(e,b);Tub(this.b,ild($Ud,{272:1,322:1},137,[d,c,e,(this.c=new dkb,Sib(this.c),Oib(this.c),Thb(this.c,WGf,(xUe(),xUe(),wUe),true),Qhb(this.c,iEf,0,true),x=new JPe(C3f),y=new JPe(E3f),z=new JPe(I3f),A=new JPe(K3f),Phb(this.c,fEf,ild(dVd,{272:1,322:1},190,[x,y,z,A]),true),Thb(this.c,NFf,wUe,true),Thb(this.c,hEf,wUe,true),Shb(this.c,eEf,p1c(e1c())),Thb(this.c,gEf,wUe,false),Qhb(this.c,iEf,0,true),Thb(this.c,gEf,wUe,false),Thb(this.c,OFf,wUe,true),Thb(this.c,r1f,wUe,true),this.c)]))}
var y3f='/response/data/recordlist/*',Q3f='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',b4f='AsyncLoader19',S3f='DATA',D3f='Data 1',F3f='Data 2',J3f='Data 3',L3f='Data 4',R3f='Test RPC',W3f='TestRestDataSourceData$1',X3f='TestRestDataSourcePresenter',P3f='TestRestDataSourceServlet?method=add',N3f='TestRestDataSourceServlet?method=fetch',T3f='TestRestDataSourceServlet?method=rpc',Z3f='TestRestDataSourceView',$3f='TestRestDataSourceView$1',_3f='TestRestDataSourceView$1$1',a4f='TestRestDataSourceView$2',V3f='com.gdn.venice.client.app.testrestdatasource.data.',Y3f='com.gdn.venice.client.app.testrestdatasource.view.',C3f='data1',E3f='data2',H3f='data2/name',I3f='data3',K3f='data4',U3f='runCallbacks19',G3f='valueXPath';var c1c=null;_=s2c.prototype=f1c.prototype=new g1c;_.gC=function t2c(){return eKd};_.te=function u2c(b){var c;return c=this.ud(),c.__transformRequest(b.fd())};_.ue=function v2c(b,c,d){var e;e=this.ud();e.__transformResponse(b.fd(),c.fd(),d)};_.cM={87:1,217:1,319:1};_=y2c.prototype=w2c.prototype=new JX;_.gC=function z2c(){return hKd};_.Rc=function A2c(){mne(this.g,this,new lqe((O3c(),M3c),this))};_.cM={87:1,309:1};_=Q2c.prototype=N2c.prototype=new uZ;_.Xc=function R2c(){return this.b};_.gC=function S2c(){return lKd};_.cM={275:1};_.b=null;_.c=null;_=V2c.prototype=T2c.prototype=new YH;_.gC=function W2c(){return jKd};_.Yc=function X2c(b){var c;c=new Ire;c.M[bdf]=S3f;c.M[cdf]=Wbd()+T3f;c.M[edf]=fdf;wHe(c.M,gdf,(xUe(),xUe(),wUe));wHe(c.M,hdf,vUe);oze(c,new $2c)};_.cM={292:1,324:1};_=$2c.prototype=Y2c.prototype=new YH;_.Sc=function _2c(b,c,d){$wnd.isc.say(BJf)};_.gC=function a3c(){return iKd};_.cM={};_=d3c.prototype=b3c.prototype=new YH;_.gC=function e3c(){return kKd};_.Yc=function f3c(b){var c;c=this.b.c.ud();c.startEditingNew()};_.cM={292:1,324:1};_.b=null;_=O$d.prototype=I$d.prototype=new YH;_.gC=function P$d(){return AMd};_.Re=function T$d(){N$d()};_.cM={};var eKd=OUe(V3f,W3f),hKd=OUe(ruf,X3f),lKd=OUe(Y3f,Z3f),jKd=OUe(Y3f,$3f),iKd=OUe(Y3f,_3f),kKd=OUe(Y3f,a4f),AMd=OUe(kyf,b4f);$entry(Q$d)();