function o4(){}
function C5(){}
function T5(){}
function _5(){}
function Z5(){}
function e6(){}
function c6(){}
function h6(){}
function dIb(){}
function ZHb(){}
function j6(b){this.b=b}
function y5(){s5.call(this)}
function Hw(b){b.c.Wd(ms(b.b.b))}
function yp(b,c,d){return new E5(b,c,d)}
function E5(b,c,d){Sz.call(this,b,c);this.c=d;mmb(this.i,59).Wb(this)}
function fIb(){aIb=new dIb;Gdb((Ddb(),Cdb),21);!!$stats&&$stats(veb(jjd,yHc,-1,-1));aIb.Id();!!$stats&&$stats(veb(jjd,D$c,-1,-1))}
function cIb(){var b,d,e;while($Hb){d=Zbb;e=$Hb;$Hb=$Hb.c;!$Hb&&(_Hb=null);if(!d){Hw(e.b)}else{try{Hw(e.b)}catch(b){b=MBb(b);if(!pmb(b,141))throw b}}}}
function v4(g,b){var c;if(g.oc()){var d=g.Ob();c=d.getProperty(b)}else{var e=g.b;if(e[b]!=undefined){c=e[b]}else{var f=g.d;c=eval(cjd+f+djd+b+ejd)}}return c===undefined?null:c}
function ms(b){var c;!b.xb&&(b.xb=(c=yp((!b.Gb&&(b.Gb=new dXb),b.Gb),(!b.yb&&(b.yb=new W5),b.yb),(!b.wb&&(b.wb=new L5),b.wb),!b.Fb&&(b.Fb=(new WVb)._d(new FVb,new JVb))),c.Qb(),c));return b.xb}
function n4(){var b,c,d,e,f,g,i,j;if(l4){return l4}else{l4=new y5;z4(l4,Nid,Oid,false);v4(l4,Nid);g=new d0b;g.g[C9c]=(r7b(),n7b).b;g.g[Pid]=(F7b(),B7b).b;b=new d0b;b.g[C9c]=l7b.b;b.g[Pid]=B7b.b;j=new d0b;j.g[C9c]=p7b.b;j.g[Pid]=B7b.b;i=new d0b;i.g[C9c]=o7b.b;i.g[Pid]=B7b.b;B4(l4,c9c,$lb(PAb,{137:1,239:1},167,[g,b,j,i]));c=new P0b(Qid,Rid);Sdc(c.g,b0c,(Joc(),Joc(),Ioc));d=new P0b(Sid,Tid);d.g[Uid]=Vid;e=new P0b(Wid,Xid);f=new P0b(Yid,Zid);$4(l4,$lb(NAb,{137:1,239:1},165,[c,d,e,f]));z4(l4,$id,Heb()+_id,false);z4(l4,ajd,Heb()+bjd,false);return l4}}
function W5(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new IG;d=new Qec;fF(d,iFc,(Hac(),Bac).b,true);jF(d,sFc,nqc(2));eF(d)?(i=d.Ob(),i.setProperty(oEc,lEc),undefined):(d.i[oEc]=lEc,undefined);eF(d)?(n=d.Ob(),n.setProperty(kEc,20),undefined):(d.i[kEc]=20,undefined);eF(d)?(q=d.Ob(),q.setProperty(fFc,fjd),undefined):(d.i[fFc]=fjd,undefined);c=new Eec(gjd);TF(c,new _5);e=new mnc;b=new snc;eF(b)?(t=b.Ob(),t.setProperty(u$c,d_c),undefined):(b.i[u$c]=d_c,undefined);eF(b)?(w=b.Ob(),w.setProperty(k0c,RLc),undefined):(b.i[k0c]=RLc,undefined);TF(b,new j6(this));knc(e,b);zG(this.b,$lb(nBb,{137:1,239:1},194,[d,c,e,(this.c=new PK,cG(this.c),_F(this.c),mF(this.c,G0c,(Joc(),Joc(),Ioc),true),iF(this.c,H0c,0),x=new bkc(Qid),y=new bkc(Sid),z=new bkc(Wid),A=new bkc(Yid),hF(this.c,i_c,$lb(rBb,{137:1,239:1},201,[x,y,z,A]),true),mF(this.c,j_c,Ioc,true),mF(this.c,I0c,Ioc,true),kF(this.c,g_c,x4(n4())),mF(this.c,h_c,Ioc,false),iF(this.c,H0c,0),mF(this.c,h_c,Ioc,false),mF(this.c,C_c,Ioc,true),mF(this.c,D_c,Ioc,true),this.c)]))}
var Oid='/response/data/recordlist/*',fjd='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',sjd='AsyncLoader21',hjd='DATA',Rid='Data 1',Tid='Data 2',Xid='Data 3',Zid='Data 4',gjd='Test RPC',ljd='TestRestDataSourceData$1',mjd='TestRestDataSourcePresenter',bjd='TestRestDataSourceServlet?method=add',_id='TestRestDataSourceServlet?method=fetch',ijd='TestRestDataSourceServlet?method=rpc',ojd='TestRestDataSourceView',pjd='TestRestDataSourceView$1',qjd='TestRestDataSourceView$1$1',rjd='TestRestDataSourceView$2',ajd='addDataURL',kjd='com.gdn.venice.client.app.testrestdatasource.data.',njd='com.gdn.venice.client.app.testrestdatasource.view.',Qid='data1',Sid='data2',Vid='data2/name',Wid='data3',Yid='data4',jjd='runCallbacks21',Uid='valueXPath';var l4=null;_=y5.prototype=o4.prototype=new p4;_.gC=function z5(){return qsb};_.jd=function A5(b){var c;return c=this.nc(),c.__transformRequest(b.Ob())};_.kd=function B5(b,c,d){var e;e=this.nc();e.__transformResponse(b.Ob(),c.Ob(),d)};_.cM={30:1,72:1,232:1};_=E5.prototype=C5.prototype=new vz;_.gC=function F5(){return tsb};_.Sb=function G5(){cXb(this.f,this,new b$b((U6(),S6),this))};_.cM={72:1,222:1};_=W5.prototype=T5.prototype=new XA;_.Xb=function X5(){return this.b};_.gC=function Y5(){return xsb};_.cM={59:1};_.b=null;_.c=null;_=_5.prototype=Z5.prototype=new No;_.gC=function a6(){return vsb};_.Yb=function b6(b){var c;c=new x_b;c.g[zFc]=hjd;c.g[SEc]=Heb()+ijd;c.g[UEc]=VEc;Sdc(c.g,WEc,(Joc(),Joc(),Ioc));Sdc(c.g,XEc,Hoc);D6b(c,new e6)};_.cM={212:1,241:1};_=e6.prototype=c6.prototype=new No;_.dd=function f6(b,c,d){$wnd.isc.say(d0c+c)};_.gC=function g6(){return usb};_.cM={};_=j6.prototype=h6.prototype=new No;_.gC=function k6(){return wsb};_.Yb=function l6(b){var c;c=this.b.c.nc();c.startEditingNew()};_.cM={212:1,241:1};_.b=null;_=dIb.prototype=ZHb.prototype=new No;_.gC=function eIb(){return Nub};_.Id=function iIb(){cIb()};_.cM={};var qsb=$oc(kjd,ljd),tsb=$oc(nTc,mjd),xsb=$oc(njd,ojd),vsb=$oc(njd,pjd),usb=$oc(njd,qjd),wsb=$oc(njd,rjd),Nub=$oc(lWc,sjd);$entry(fIb)();