function f1c(){}
function w2c(){}
function N2c(){}
function V2c(){}
function T2c(){}
function $2c(){}
function Y2c(){}
function b3c(){}
function x8d(){}
function r8d(){}
function d3c(b){this.b=b}
function s2c(){m2c.call(this)}
function jW(b){b.c.Ze(MN(b.b.b))}
function jJ(b,c,d){return new y2c(b,c,d)}
function y2c(b,c,d){eY.call(this,b,c);this.d=d;uld(this.j,275).Wc(this)}
function z8d(){u8d=new x8d;Vad((Sad(),Rad),41);!!$stats&&$stats(Kbd(asg,Yhf,-1,-1));u8d.Re();!!$stats&&$stats(Kbd(asg,FFf,-1,-1))}
function w8d(){var b,d,e;while(s8d){d=$8c;e=s8d;s8d=s8d.c;!s8d&&(t8d=null);if(!d){jW(e.b)}else{try{jW(e.b)}catch(b){b=wVd(b);if(!xld(b,209))throw b}}}}
function MN(b){var c;!b.Ac&&(b.Ac=(c=jJ((!b.Jc&&(b.Jc=new one),b.Jc),(!b.Bc&&(b.Bc=new Q2c),b.Bc),(!b.zc&&(b.zc=new F2c),b.zc),!b.Ic&&(b.Ic=(new fme).df(new Qle,new Ule))),c.Pc(),c));return b.Ac}
function e1c(){var b,c,d,e,f,g,i,j;if(c1c){return c1c}else{c1c=new s2c;r1c(c1c,Frg,Grg,false);g=new sse;g.M[Hrg]=(CAe(),yAe).b;g.M[Irg]=(QAe(),MAe).b;b=new sse;b.M[Hrg]=wAe.b;b.M[Irg]=MAe.b;j=new sse;j.M[Hrg]=AAe.b;j.M[Irg]=MAe.b;i=new sse;i.M[Hrg]=zAe.b;i.M[Irg]=MAe.b;u1c(c1c,Jrg,gld(uUd,{272:1,322:1},105,[g,b,j,i]));c=new Bte(Krg,Lrg);xHe(c.M,EDf,(yUe(),yUe(),xUe));d=new Bte(Mrg,Nrg);d.M[Org]=Prg;e=new Bte(Qrg,Rrg);f=new Bte(Srg,Trg);U1c(c1c,gld(sUd,{272:1,322:1},103,[c,d,e,f]));r1c(c1c,Urg,Wbd()+Vrg,false);r1c(c1c,Wrg,Wbd()+Xrg,false);return c1c}}
function Q2c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new avb;d=new zIe;Nhb(d,Edf,(ZDe(),TDe).b,true);Rhb(d,Qdf,lWe(2));Mhb(d)?(i=d.fd(),i.setProperty(ocf,lcf),undefined):(d.o[ocf]=lcf,undefined);Mhb(d)?(n=d.fd(),n.setProperty(kcf,20),undefined):(d.o[kcf]=20,undefined);Mhb(d)?(q=d.fd(),q.setProperty(Bdf,Yrg),undefined):(d.o[Bdf]=Yrg,undefined);c=new nIe(Zrg);zib(c,new V2c);e=new gTe;b=new mTe;Mhb(b)?(t=b.fd(),t.setProperty(HEf,XLf),undefined):(b.o[HEf]=XLf,undefined);Mhb(b)?(w=b.fd(),w.setProperty(JEf,mmf),undefined):(b.o[JEf]=mmf,undefined);zib(b,new d3c(this));eTe(e,b);Tub(this.b,gld(YUd,{272:1,322:1},137,[d,c,e,(this.c=new dkb,Sib(this.c),Oib(this.c),Thb(this.c,YEf,(yUe(),yUe(),xUe),true),Qhb(this.c,ZEf,0,true),x=new KPe(Krg),y=new KPe(Mrg),z=new KPe(Qrg),A=new KPe(Srg),Phb(this.c,lEf,gld(bVd,{272:1,322:1},190,[x,y,z,A]),true),Thb(this.c,$Ef,xUe,true),Thb(this.c,_Ef,xUe,true),Shb(this.c,kEf,p1c(e1c())),Thb(this.c,mEf,xUe,false),Qhb(this.c,ZEf,0,true),Thb(this.c,mEf,xUe,false),Thb(this.c,aFf,xUe,true),Thb(this.c,hYf,xUe,true),this.c)]))}
var Grg='/response/data/recordlist/*',Yrg='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',jsg='AsyncLoader41',$rg='DATA',Lrg='Data 1',Nrg='Data 2',Rrg='Data 3',Trg='Data 4',Zrg='Test RPC',csg='TestRestDataSourceData$1',dsg='TestRestDataSourcePresenter',Xrg='TestRestDataSourceServlet?method=add',Vrg='TestRestDataSourceServlet?method=fetch',_rg='TestRestDataSourceServlet?method=rpc',fsg='TestRestDataSourceView',gsg='TestRestDataSourceView$1',hsg='TestRestDataSourceView$1$1',isg='TestRestDataSourceView$2',bsg='com.gdn.venice.client.app.testrestdatasource.data.',esg='com.gdn.venice.client.app.testrestdatasource.view.',Krg='data1',Mrg='data2',Prg='data2/name',Qrg='data3',Srg='data4',asg='runCallbacks41',Org='valueXPath';var c1c=null;_=s2c.prototype=f1c.prototype=new g1c;_.gC=function t2c(){return cKd};_.te=function u2c(b){var c;return c=this.ud(),c.__transformRequest(b.fd())};_.ue=function v2c(b,c,d){var e;e=this.ud();e.__transformResponse(b.fd(),c.fd(),d)};_.cM={87:1,217:1,319:1};_=y2c.prototype=w2c.prototype=new JX;_.gC=function z2c(){return fKd};_.Rc=function A2c(){nne(this.g,this,new mqe((O3c(),M3c),this))};_.cM={87:1,309:1};_=Q2c.prototype=N2c.prototype=new uZ;_.Xc=function R2c(){return this.b};_.gC=function S2c(){return jKd};_.cM={275:1};_.b=null;_.c=null;_=V2c.prototype=T2c.prototype=new YH;_.gC=function W2c(){return hKd};_.Yc=function X2c(b){var c;c=new Jre;c.M[cdf]=$rg;c.M[ddf]=Wbd()+_rg;c.M[fdf]=gdf;xHe(c.M,hdf,(yUe(),yUe(),xUe));xHe(c.M,idf,wUe);pze(c,new $2c)};_.cM={292:1,324:1};_=$2c.prototype=Y2c.prototype=new YH;_.Sc=function _2c(b,c,d){$wnd.isc.say(mDf)};_.gC=function a3c(){return gKd};_.cM={};_=d3c.prototype=b3c.prototype=new YH;_.gC=function e3c(){return iKd};_.Yc=function f3c(b){var c;c=this.b.c.ud();c.startEditingNew()};_.cM={292:1,324:1};_.b=null;_=x8d.prototype=r8d.prototype=new YH;_.gC=function y8d(){return TNd};_.Re=function C8d(){w8d()};_.cM={};var cKd=PUe(bsg,csg),fKd=PUe(vuf,dsg),jKd=PUe(esg,fsg),hKd=PUe(esg,gsg),gKd=PUe(esg,hsg),iKd=PUe(esg,isg),TNd=PUe(oyf,jsg);$entry(z8d)();