function i1c(){}
function z2c(){}
function Q2c(){}
function Y2c(){}
function W2c(){}
function _2c(){}
function b3c(){}
function e3c(){}
function g3d(){}
function a3d(){}
function g3c(b){this.b=b}
function v2c(){p2c.call(this)}
function GT(b){b.c.bf(QN(b.b.b))}
function nJ(b,c,d){return new B2c(b,c,d)}
function B2c(b,c,d){iY.call(this,b,c);this.d=d;Sld(this.j,275).Wc(this)}
function i3d(){d3d=new g3d;Yad((Vad(),Uad),28);!!$stats&&$stats(Nbd(Xeg,Aif,-1,-1));d3d.Ve();!!$stats&&$stats(Nbd(Xeg,qEf,-1,-1))}
function f3d(){var b,d,e;while(b3d){d=b9c;e=b3d;b3d=b3d.c;!b3d&&(c3d=null);if(!d){GT(e.b)}else{try{GT(e.b)}catch(b){b=YVd(b);if(!Vld(b,209))throw b}}}}
function QN(b){var c;!b.Ac&&(b.Ac=(c=nJ((!b.Jc&&(b.Jc=new Sne),b.Jc),(!b.Bc&&(b.Bc=new T2c),b.Bc),(!b.zc&&(b.zc=new I2c),b.zc),!b.Ic&&(b.Ic=(new Jme).hf(new sme,new wme))),c.Pc(),c));return b.Ac}
function h1c(){var b,c,d,e,f,g,i,j;if(f1c){return f1c}else{f1c=new v2c;u1c(f1c,Aeg,Beg,false);g=new Wse;g.M[Ceg]=(eBe(),aBe).b;g.M[Deg]=(sBe(),oBe).b;b=new Wse;b.M[Ceg]=$Ae.b;b.M[Deg]=oBe.b;j=new Wse;j.M[Ceg]=cBe.b;j.M[Deg]=oBe.b;i=new Wse;i.M[Ceg]=bBe.b;i.M[Deg]=oBe.b;x1c(f1c,Eeg,Eld(WUd,{272:1,322:1},105,[g,b,j,i]));c=new due(Feg,Geg);_He(c.M,cEf,(aVe(),aVe(),_Ue));d=new due(Heg,Ieg);d.M[Jeg]=Keg;e=new due(Leg,Meg);f=new due(Neg,Oeg);X1c(f1c,Eld(UUd,{272:1,322:1},103,[c,d,e,f]));u1c(f1c,Peg,Zbd()+Qeg,false);u1c(f1c,Reg,Zbd()+Seg,false);return f1c}}
function T2c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new evb;d=new bJe;Rhb(d,gef,(BEe(),vEe).b,true);Vhb(d,sef,PWe(2));Qhb(d)?(i=d.fd(),i.setProperty(Scf,Pcf),undefined):(d.o[Scf]=Pcf,undefined);Qhb(d)?(n=d.fd(),n.setProperty(Ocf,20),undefined):(d.o[Ocf]=20,undefined);Qhb(d)?(q=d.fd(),q.setProperty(def,Teg),undefined):(d.o[def]=Teg,undefined);c=new RIe(Ueg);Dib(c,new Y2c);e=new KTe;b=new QTe;Qhb(b)?(t=b.fd(),t.setProperty(UFf,DMf),undefined):(b.o[UFf]=DMf,undefined);Qhb(b)?(w=b.fd(),w.setProperty(WFf,Pmf),undefined):(b.o[WFf]=Pmf,undefined);Dib(b,new g3c(this));ITe(e,b);Xub(this.b,Eld(yVd,{272:1,322:1},137,[d,c,e,(this.c=new hkb,Wib(this.c),Sib(this.c),Xhb(this.c,jGf,(aVe(),aVe(),_Ue),true),Uhb(this.c,kGf,0,true),x=new mQe(Feg),y=new mQe(Heg),z=new mQe(Leg),A=new mQe(Neg),Thb(this.c,gEf,Eld(DVd,{272:1,322:1},190,[x,y,z,A]),true),Xhb(this.c,jEf,_Ue,true),Xhb(this.c,mEf,_Ue,true),Whb(this.c,fEf,s1c(h1c())),Xhb(this.c,hEf,_Ue,false),Uhb(this.c,kGf,0,true),Xhb(this.c,hEf,_Ue,false),Xhb(this.c,kEf,_Ue,true),Xhb(this.c,IMf,_Ue,true),this.c)]))}
var Beg='/response/data/recordlist/*',Teg='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',efg='AsyncLoader28',Veg='DATA',Geg='Data 1',Ieg='Data 2',Meg='Data 3',Oeg='Data 4',Ueg='Test RPC',Zeg='TestRestDataSourceData$1',$eg='TestRestDataSourcePresenter',Seg='TestRestDataSourceServlet?method=add',Qeg='TestRestDataSourceServlet?method=fetch',Weg='TestRestDataSourceServlet?method=rpc',afg='TestRestDataSourceView',bfg='TestRestDataSourceView$1',cfg='TestRestDataSourceView$1$1',dfg='TestRestDataSourceView$2',Yeg='com.gdn.venice.client.app.testrestdatasource.data.',_eg='com.gdn.venice.client.app.testrestdatasource.view.',Feg='data1',Heg='data2',Keg='data2/name',Leg='data3',Neg='data4',Xeg='runCallbacks28',Jeg='valueXPath';var f1c=null;_=v2c.prototype=i1c.prototype=new j1c;_.gC=function w2c(){return AKd};_.te=function x2c(b){var c;return c=this.ud(),c.__transformRequest(b.fd())};_.ue=function y2c(b,c,d){var e;e=this.ud();e.__transformResponse(b.fd(),c.fd(),d)};_.cM={87:1,217:1,319:1};_=B2c.prototype=z2c.prototype=new NX;_.gC=function C2c(){return DKd};_.Rc=function D2c(){Rne(this.g,this,new Qqe((R3c(),P3c),this))};_.cM={87:1,309:1};_=T2c.prototype=Q2c.prototype=new yZ;_.Xc=function U2c(){return this.b};_.gC=function V2c(){return HKd};_.cM={275:1};_.b=null;_.c=null;_=Y2c.prototype=W2c.prototype=new aI;_.gC=function Z2c(){return FKd};_.Yc=function $2c(b){var c;c=new lse;c.M[Gdf]=Veg;c.M[Hdf]=Zbd()+Weg;c.M[Jdf]=Kdf;_He(c.M,Ldf,(aVe(),aVe(),_Ue));_He(c.M,Mdf,$Ue);Tze(c,new b3c)};_.cM={292:1,324:1};_=b3c.prototype=_2c.prototype=new aI;_.Sc=function c3c(b,c,d){$wnd.isc.say(FEf)};_.gC=function d3c(){return EKd};_.cM={};_=g3c.prototype=e3c.prototype=new aI;_.gC=function h3c(){return GKd};_.Yc=function i3c(b){var c;c=this.b.c.ud();c.startEditingNew()};_.cM={292:1,324:1};_.b=null;_=g3d.prototype=a3d.prototype=new aI;_.gC=function h3d(){return BNd};_.Ve=function l3d(){f3d()};_.cM={};var AKd=rVe(Yeg,Zeg),DKd=rVe(Xuf,$eg),HKd=rVe(_eg,afg),FKd=rVe(_eg,bfg),EKd=rVe(_eg,cfg),GKd=rVe(_eg,dfg),BNd=rVe(Tyf,efg);$entry(i3d)();