function i1c(){}
function z2c(){}
function Q2c(){}
function Y2c(){}
function W2c(){}
function _2c(){}
function b3c(){}
function e3c(){}
function Y$d(){}
function S$d(){}
function g3c(b){this.b=b}
function v2c(){p2c.call(this)}
function OR(b){b.c.gf(PN(b.b.b))}
function mJ(b,c,d){return new B2c(b,c,d)}
function B2c(b,c,d){hY.call(this,b,c);this.d=d;Dld(this.j,275).Wc(this)}
function $$d(){V$d=new Y$d;Xad((Uad(),Tad),19);!!$stats&&$stats(Mbd(S5f,fjf,-1,-1));V$d.Ue();!!$stats&&$stats(Mbd(S5f,sGf,-1,-1))}
function X$d(){var b,d,e;while(T$d){d=b9c;e=T$d;T$d=T$d.c;!T$d&&(U$d=null);if(!d){OR(e.b)}else{try{OR(e.b)}catch(b){b=IVd(b);if(!Gld(b,209))throw b}}}}
function PN(b){var c;!b.Ac&&(b.Ac=(c=mJ((!b.Jc&&(b.Jc=new voe),b.Jc),(!b.Bc&&(b.Bc=new T2c),b.Bc),(!b.zc&&(b.zc=new I2c),b.zc),!b.Ic&&(b.Ic=(new mne).of(new Xme,new _me))),c.Pc(),c));return b.Ac}
function h1c(){var b,c,d,e,f,g,i,j;if(f1c){return f1c}else{f1c=new v2c;u1c(f1c,v5f,w5f,false);g=new zte;g.M[x5f]=(JBe(),FBe).b;g.M[y5f]=(XBe(),TBe).b;b=new zte;b.M[x5f]=DBe.b;b.M[y5f]=TBe.b;j=new zte;j.M[x5f]=HBe.b;j.M[y5f]=TBe.b;i=new zte;i.M[x5f]=GBe.b;i.M[y5f]=TBe.b;x1c(f1c,z5f,pld(GUd,{272:1,321:1},105,[g,b,j,i]));c=new Iue(A5f,B5f);EIe(c.M,aGf,(FVe(),FVe(),EVe));d=new Iue(C5f,D5f);d.M[E5f]=F5f;e=new Iue(G5f,H5f);f=new Iue(I5f,J5f);X1c(f1c,pld(EUd,{272:1,321:1},103,[c,d,e,f]));u1c(f1c,K5f,Ybd()+L5f,false);u1c(f1c,M5f,Ybd()+N5f,false);return f1c}}
function T2c(){var b,c,d,e,i,n,q,t,w,x,y,z,A;this.b=new dvb;d=new GJe;Qhb(d,Nef,(eFe(),$Ee).b,true);Uhb(d,Zef,sXe(2));Phb(d)?(i=d.fd(),i.setProperty(wdf,tdf),undefined):(d.o[wdf]=tdf,undefined);Phb(d)?(n=d.fd(),n.setProperty(sdf,20),undefined):(d.o[sdf]=20,undefined);Phb(d)?(q=d.fd(),q.setProperty(Kef,O5f),undefined):(d.o[Kef]=O5f,undefined);c=new uJe(P5f);Cib(c,new Y2c);e=new nUe;b=new tUe;Phb(b)?(t=b.fd(),t.setProperty(FHf,GHf),undefined):(b.o[FHf]=GHf,undefined);Phb(b)?(w=b.fd(),w.setProperty(HHf,fof),undefined):(b.o[HHf]=fof,undefined);Cib(b,new g3c(this));lUe(e,b);Wub(this.b,pld(iVd,{272:1,321:1},137,[d,c,e,(this.c=new gkb,Vib(this.c),Rib(this.c),Whb(this.c,UIf,(FVe(),FVe(),EVe),true),Thb(this.c,gGf,0,true),x=new RQe(A5f),y=new RQe(C5f),z=new RQe(G5f),A=new RQe(I5f),Shb(this.c,dGf,pld(nVd,{272:1,321:1},190,[x,y,z,A]),true),Whb(this.c,LHf,EVe,true),Whb(this.c,fGf,EVe,true),Vhb(this.c,cGf,s1c(h1c())),Whb(this.c,eGf,EVe,false),Thb(this.c,gGf,0,true),Whb(this.c,eGf,EVe,false),Whb(this.c,MHf,EVe,true),Whb(this.c,p3f,EVe,true),this.c)]))}
var w5f='/response/data/recordlist/*',O5f='<span style="font-size:14px;font-weight:bold;">Test Rest Data Source<\/span>',_5f='AsyncLoader19',Q5f='DATA',B5f='Data 1',D5f='Data 2',H5f='Data 3',J5f='Data 4',P5f='Test RPC',U5f='TestRestDataSourceData$1',V5f='TestRestDataSourcePresenter',N5f='TestRestDataSourceServlet?method=add',L5f='TestRestDataSourceServlet?method=fetch',R5f='TestRestDataSourceServlet?method=rpc',X5f='TestRestDataSourceView',Y5f='TestRestDataSourceView$1',Z5f='TestRestDataSourceView$1$1',$5f='TestRestDataSourceView$2',T5f='com.gdn.venice.client.app.testrestdatasource.data.',W5f='com.gdn.venice.client.app.testrestdatasource.view.',A5f='data1',C5f='data2',F5f='data2/name',G5f='data3',I5f='data4',S5f='runCallbacks19',E5f='valueXPath';var f1c=null;_=v2c.prototype=i1c.prototype=new j1c;_.gC=function w2c(){return lKd};_.te=function x2c(b){var c;return c=this.ud(),c.__transformRequest(b.fd())};_.ue=function y2c(b,c,d){var e;e=this.ud();e.__transformResponse(b.fd(),c.fd(),d)};_.cM={87:1,217:1,318:1};_=B2c.prototype=z2c.prototype=new MX;_.gC=function C2c(){return oKd};_.Rc=function D2c(){uoe(this.g,this,new tre((R3c(),P3c),this))};_.cM={87:1,308:1};_=T2c.prototype=Q2c.prototype=new xZ;_.Xc=function U2c(){return this.b};_.gC=function V2c(){return sKd};_.cM={275:1};_.b=null;_.c=null;_=Y2c.prototype=W2c.prototype=new _H;_.gC=function Z2c(){return qKd};_.Yc=function $2c(b){var c;c=new Qse;c.M[kef]=Q5f;c.M[lef]=Ybd()+R5f;c.M[nef]=oef;EIe(c.M,pef,(FVe(),FVe(),EVe));EIe(c.M,qef,DVe);wAe(c,new b3c)};_.cM={291:1,323:1};_=b3c.prototype=_2c.prototype=new _H;_.Sc=function c3c(b,c,d){$wnd.isc.say(zLf)};_.gC=function d3c(){return pKd};_.cM={};_=g3c.prototype=e3c.prototype=new _H;_.gC=function h3c(){return rKd};_.Yc=function i3c(b){var c;c=this.b.c.ud();c.startEditingNew()};_.cM={291:1,323:1};_.b=null;_=Y$d.prototype=S$d.prototype=new _H;_.gC=function Z$d(){return GMd};_.Ue=function b_d(){X$d()};_.cM={};var lKd=WVe(T5f,U5f),oKd=WVe(mwf,V5f),sKd=WVe(W5f,X5f),qKd=WVe(W5f,Y5f),pKd=WVe(W5f,Z5f),rKd=WVe(W5f,$5f),GMd=WVe(eAf,_5f);$entry($$d)();